<a href="https://colab.research.google.com/github/phillipster/subsurface-element-mapping/blob/main/S24_Summer_Church_Nearby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
API_KEY = 'AIzaSyBbPzmWZUvD58nBY9HY1i0gAzlh2QpqsLo'

import requests
import pandas as pd

In [ ]:
import requests
import time
location = '40.752301	,-73.799000	'
radius = 500
place_type = 'church'
places = []

def fetch_all_places(api_key, location, radius, place_type):
    # Google Places API endpoint
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Initial parameters for the API request
    params = {
        'key': API_KEY,
        'location': location,
        'radius': radius,
        'type': place_type
    }

    # List to store all places

    while True:
        # Make the API request
        response = requests.get(url, params=params)
        res = response.json()

        # Check if the request was successful
        if res['status'] == 'OK':
            # Extract places
            places.extend([(place['name'], place['vicinity']) for place in res['results']])

            # Check for the presence of a 'next_page_token' in the response
            if 'next_page_token' in res:
                params['pagetoken'] = res['next_page_token']
            else:
                break  # No more pages to fetch

            # Important: There is a short delay needed between requests for the next page token to become valid
            time.sleep(10)
        else:
            print("Failed to fetch results:", res['status'])
            break

    return places

# Example usage:
api_key = API_KEY  # Replace 'YOUR_API_KEY' with your actual Google Cloud API key
location = '40.752301	,-73.799000	'
radius = 500
place_type = 'church'

# Fetch all churches
churches = fetch_all_places(api_key, location, radius, place_type)
for name, vicinity in churches:
    print(f"Name: {name}, Location: {vicinity}")

Counter:  1
Name: Trinity Church, Address: 89 Broadway, New York
Counter:  2
Name: St. Paul's Chapel, Address: 209 Broadway, New York
Counter:  3
Name: St Peter's Roman Catholic Church, Address: 22 Barclay Street, New York
Counter:  4
Name: St. Andrew Roman Catholic Church, Address: 20 Cardinal Hayes Place, New York
Counter:  5
Name: Our Lady of Victory Church, Address: 22 Barclay Street, New York
Counter:  6
Name: St. Elizabeth Ann Seton Shrine, Address: 7 State Street, New York
Counter:  7
Name: RCM Group, Address: 355 South End Avenue, New York
Counter:  8
Name: Revival Partners LLC, Address: 355 South End Avenue, New York
Counter:  9
Name: Liberty Church New York City, Address: 55 Broadway, New York
Counter:  10
Name: St. Nicholas National Shrine, Address: 130 Liberty Street, New York
Counter:  11
Name: Faith Evangelistic Ministries, Address: kt # 2, New York
Counter:  12
Name: River NYC Church, Address: 75 Murray Street, New York
Counter:  13
Name: Kingdom Hall of Jehovah's Witnesses, Address: 336 Pearl Street, New York
Counter:  14
Name: Rev. Christie Hord, Address: 111 Broadway, New York
Counter:  15
Name: jesus week nyc, Address: 2 Washington Street, New York
Counter:  16
Name: A New Heritage of Giving, Address: 120 Wall Street, New York
Counter:  17
Name: Our Lady of the Rosary, Address: 7 State Street, New York
Counter:  18
Name: Orthodox Union, Address: 40 Rector Street, New York
Counter:  19
Name: Wall Street Synagogue, Address: 47 Beekman Street, New York
Counter:  20
Name: John Street United Methodist Church, Address: 44 John Street, New York

In [ ]:
location = '40.752301	,-73.799000	'
radius = 500
place_type = 'church'

url = (
    f'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
    f'?location={location}'
    f'&radius={radius}'
    f'&type={place_type}'
    f'&key={API_KEY}'
)

response = requests.get(url)

places = response.json()
counter = 0
if places['status'] == 'OK':
    for place in places['results']:
        name = place['name']
        address = place.get('vicinity', 'No address available')
        counter += 1
        print("Counter: ",counter)
        print(f'Name: {name}, Address: {address}')
else:
    print(f"Error: {places['status']}")

                                   Name                            Address  \
0                        Trinity Church              89 Broadway, New York
1                     St. Paul's Chapel             209 Broadway, New York
2      St Peter's Roman Catholic Church        22 Barclay Street, New York
3      St. Andrew Roman Catholic Church  20 Cardinal Hayes Place, New York
4            Our Lady of Victory Church        22 Barclay Street, New York
5        St. Elizabeth Ann Seton Shrine           7 State Street, New York
6                             RCM Group     355 South End Avenue, New York
7                  Revival Partners LLC     355 South End Avenue, New York
8          Liberty Church New York City              55 Broadway, New York
9          St. Nicholas National Shrine       130 Liberty Street, New York
10        Faith Evangelistic Ministries                   kt # 2, New York
11                     River NYC Church         75 Murray Street, New York
12  Kingdom Hall of Jehovah's Witnesses         336 Pearl Street, New York
13                   Rev. Christie Hord             111 Broadway, New York
14                       jesus week nyc      2 Washington Street, New York
15             A New Heritage of Giving          120 Wall Street, New York
16               Our Lady of the Rosary           7 State Street, New York
17                       Orthodox Union         40 Rector Street, New York
18                Wall Street Synagogue        47 Beekman Street, New York
19  John Street United Methodist Church           44 John Street, New York

     Latitude  Longitude
0   40.707893 -74.011790
1   40.711328 -74.009183
2   40.712483 -74.009531
3   40.713344 -74.002662
4   40.706969 -74.008875
5   40.702559 -74.013774
6   40.710943 -74.016333
7   40.710503 -74.016620
8   40.706837 -74.012999
9   40.710134 -74.013203
10  40.708043 -74.007242
11  40.714827 -74.010554
12  40.709147 -74.001625
13  40.708687 -74.011505
14  40.705655 -74.015630
15  40.704751 -74.006027
16  40.702559 -74.013774
17  40.708428 -74.014726
18  40.710047 -74.005512
19  40.709175 -74.008073

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

!pip install openpyxl

import pandas as pd

file_path = '/content/drive/MyDrive/Colab Notebooks/Cemeteries in NYC.xlsx'

df = pd.read_excel(file_path)
len(df)

20

In [ ]:
df
# extract the columns important
df_filtered = df[['Name', 'Still Exists?', 'Coordinates']]
df_filtered
# Filter the DataFrame based on 'Exist or Not' status
df_exist = df_filtered[df_filtered['Still Exists?'] == 'Yes']  # or whatever the value indicating existence


# Display the filtered DataFrame
df_exist

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks/Cemeteries in NYC.xlsx'

In [1]:
# Coordinate conversion
df_exist['Coordinates'] = df_exist['Coordinates'].astype(str)

# Function to convert coordinates
def convert_coordinates(coord):
    try:
        lon, lat = coord.split()

        # Convert longitude
        if 'W' in lon:
            lon = -float(lon.replace('°W', ''))
        elif 'E' in lon:
            lon = float(lon.replace('°E', ''))

        # Convert latitude
        if 'S' in lat:
            lat = -float(lat.replace('°S', ''))
        elif 'N' in lat:
            lat = float(lat.replace('°N', ''))

        return lon, lat
    except ValueError as e:
        print(f"Error processing coordinate: '{coord}'. Error: {e}")
        return None, None

# Apply function to split coordinates
df_exist[['Longitude', 'Latitude']] = df_exist['Coordinates'].apply(lambda x: pd.Series(convert_coordinates(x)))

# Drop the original 'Coordinates' column if needed
# df.drop(columns=['Coordinates'], inplace=True)

# Display the DataFrame
df_exist

NameError: name 'df_exist' is not defined

In [ ]:
df_copy = df_exist.copy()
print("df_copy: ")
df_copy['Number of Churches Nearby'] = 0  # Initialize with 0 or any suitable default value
print(df_copy)

print("df_exist: ")
df_exist['Longitude']

Updated row 1/189
Updated row 2/189
Updated row 3/189
Updated row 4/189
Updated row 5/189
Updated row 6/189
Updated row 7/189
Updated row 8/189
Updated row 9/189
Updated row 10/189
Updated row 11/189
Updated row 12/189
Updated row 13/189
Updated row 14/189
Updated row 15/189
Updated row 16/189
Updated row 17/189
Updated row 18/189
Updated row 19/189
Updated row 20/189
Updated row 21/189
Updated row 22/189
Updated row 23/189
Updated row 24/189
Updated row 25/189
Updated row 26/189
Updated row 27/189
Updated row 28/189
Updated row 29/189
Updated row 30/189
Updated row 31/189
Updated row 32/189
Updated row 33/189
Updated row 34/189
Updated row 35/189
Updated row 36/189
Updated row 37/189
Updated row 38/189
Updated row 39/189
Updated row 40/189
Updated row 41/189
Updated row 42/189
Updated row 43/189
Updated row 44/189
Updated row 45/189
Updated row 46/189
Updated row 47/189
Updated row 48/189
Updated row 49/189
Updated row 50/189
Updated row 51/189
Updated row 52/189
Updated row 53/189
Updated row 54/189
Updated row 55/189
Updated row 56/189
Updated row 57/189
Updated row 58/189
Updated row 59/189
Updated row 60/189
Updated row 61/189
Updated row 62/189
Updated row 63/189
Updated row 64/189
Updated row 65/189
Updated row 66/189
Updated row 67/189
Updated row 68/189
Updated row 69/189
Updated row 70/189
Updated row 71/189
Updated row 72/189
Updated row 73/189
Updated row 74/189
Updated row 75/189
Updated row 76/189
Updated row 77/189
Updated row 78/189
Updated row 79/189
Updated row 80/189
Updated row 81/189
Updated row 82/189
Updated row 83/189
Updated row 84/189
Updated row 85/189
Updated row 86/189
Updated row 87/189
Updated row 88/189
Updated row 89/189
Updated row 90/189
Updated row 91/189
Updated row 92/189
Updated row 93/189
Updated row 94/189
Updated row 95/189
Updated row 96/189
Updated row 97/189
Updated row 98/189
Updated row 99/189
Updated row 100/189
Updated row 101/189
Updated row 102/189
Updated row 103/189
Updated row 104/189
Updated row 105/189
Updated row 106/189
Updated row 107/189
Updated row 108/189
Updated row 109/189
Updated row 110/189
Updated row 111/189
Updated row 112/189
Updated row 113/189
Updated row 114/189
Updated row 115/189
Updated row 116/189
Updated row 117/189
Updated row 118/189
Updated row 119/189
Updated row 120/189
Updated row 121/189
Updated row 122/189
Updated row 123/189
Updated row 124/189
Updated row 125/189
Updated row 126/189
Updated row 127/189
Updated row 128/189
Updated row 129/189
Updated row 130/189
Updated row 131/189
Updated row 132/189
Updated row 133/189
Updated row 134/189
Updated row 135/189
Updated row 136/189
Updated row 137/189
Updated row 138/189
Updated row 139/189
Updated row 140/189
Updated row 141/189
Updated row 142/189
Updated row 143/189
Updated row 144/189
Updated row 145/189
Updated row 146/189
Updated row 147/189
Updated row 148/189
Updated row 149/189
Updated row 150/189
Updated row 151/189
Updated row 152/189
Updated row 153/189
Updated row 154/189
Updated row 155/189
Updated row 156/189
Updated row 157/189
Updated row 158/189
Updated row 159/189
Updated row 160/189
Updated row 161/189
Updated row 162/189
Updated row 163/189
Updated row 164/189
Updated row 165/189
Updated row 166/189
Updated row 167/189
Updated row 168/189
Updated row 169/189
Updated row 170/189
Updated row 171/189
Updated row 172/189
Updated row 173/189
Updated row 174/189
Updated row 175/189
Updated row 176/189
Updated row 177/189
Updated row 178/189
Updated row 179/189
Updated row 180/189
Updated row 181/189
Updated row 182/189
Updated row 183/189
Updated row 184/189
Updated row 185/189
Updated row 186/189
Updated row 187/189
Updated row 188/189
Updated row 189/189
0      57
1      53
2       4
3       2
4      34
5      59
6      19
7       8
8      47
9      60
10     60
11     19
12      1
13     45
14     31
15     32
16     48
17      2
18     38
19     40
20     21
21     39
22     34
23     60
24      7
25     13
26     38
27     21
28     60
29     41
30     60
31     41
32      8
33     60
34      1
35     30
36     21
37     60
38     60
39     15
40     22
41     23
42     19
43     44
44     51
45     60
46     37
47     60
48     60
49     14
50      0
51     49
52      0
53      8
54     50
55      9
56      6
57     60
58     16
59     60
60      6
61     60
62     19
63     19
64     60
65     36
66      3
67      4
68     60
69     26
70     33
71     33
72     30
73      5
74     38
75      5
76      9
77     60
78     60
79      1
80     23
81     45
82     60
83     47
84     59
85     13
86     50
87     60
88     15
89     55
90     60
91     60
92     60
93      0
94     60
95     54
96      3
97     43
98     44
99     60
100    42
101     2
102    60
103    60
104    16
105    14
106     6
107     1
108     3
109     8
110     8
111    12
112     8
113     9
114    19
115    31
116    60
117    60
118    60
119    60
120    60
121    60
122    24
123    42
124    23
125    60
126    14
127    60
128    27
129    60
130     7
131    10
132    29
133     3
134     3
135     1
136    12
137    56
138     6
139     6
140     6
141     6
142     3
143    40
144     4
145    17
146    60
147    17
148    10
149    60
150    60
151    39
152    36
153    14
154    33
155    16
156    60
157     0
158     5
159     8
160     8
161    60
162    16
163    12
164     4
165    27
166    15
167    20
168    11
169    42
170    40
171    41
172    13
173    40
174    60
175    60
176    43
177    60
178    60
179    60
180    26
181    60
182     7
183    35
184    15
185    18
186    53
187    34
188    30
                                                  Name  \
0                              Shaaray Tefila Cemetery
1                        Brick Presbyterian Churchyard
2                         St. Andrew's Church Cemetery
3                                     Luyster Cemetery
4                          Bergen Family Burial ground
5    41St Street Reformed Presbyterian Church Cemetery
6         Port Richmond Reformed Dutch Church Cemetery
7                                    Lutheran Cemetery
8     First Reformed Dutch Church of Brooklyn cemetery
9                                     Melrose Cemetery
10   Attorney Street Methodist Protestant Church Bu...
11                                 Ocean View Cemetery
12                             Thorne-Wilkins Cemetery
13                       Public Burial Ground,Brooklyn
14                  Public Burial Ground, Fordham Road
15     Fordham Manor Church Cemetery, Kingsbridge Road
16   Bedford Street Methodist Church Graveyard and ...
17                              Mount Loretto Cemetery
18                                   Flushing Cemetery
19                   St. Paul's Churchyard Cobble Hill
20                      Catholic Cemetery, Willamsburg
21                 Bay Ridge Methodist Church Cemetery
22              Westchester Methodist Church Graveyard
23                     St. Andrew's Churchyard, Harlem
24                               Resurrection Cemetery
25                   Polish National Catholic Cemetery
26       First Presbyterian Church of Newtown Cemetery
27               Cannon Street Baptist Church Cemetery
28   West Farms Reformed Dutch Church Cemetery& Hed...
29   John Street Methodist Church Graveyard and Vaults
30                         Methodist Cemetery, Jamaica
31                           Prison Ship Martyrs Tombs
32                    Stockbridge Indian Burial Ground
33                                St.Thomas Churchyard
34                                St Joseph's Cemetery
35                              Moore Jackson cemetery
36                                  Evergreen Cemetery
37                          St. Augustine's Churchyard
38              German Catholic Cemetery, 124th Street
39                 Cherry Lane African Church Cemetery
40                   Our Lady Of Mount Carmel Cemetery
41                                New Utrecht Cemetery
42                           Cole Family Burial Ground
43                         88th Street Jewish Cemetery
44             Mendelssohn Benevolent Society Cemetery
45                   Anshe Chesed Cemeteries (45th st)
46                   Anshe Chesed Cemeteries (89th st)
47                   Watt-Pinkney Family Burial Ground
48             Shaar Hashomayim Cemetery, Williamsburg
49                            Mount St.Mary's Cemetery
50                       Presentation Sisters Cemetery
51            Flatlands Reformed Dutch Church Cemetery
52                           Pell Family Burial Ground
53                              St. Michael's Cemetery
54               St. Michael's Churchyard and Cemetery
55             St. Peter's Cemetery, West New Brighton
56                                    Rapejle Cemetery
57             Flatbush Reformed Dutch Church Cemetery
58       First Presbyterian of Throggs Neck Churchyard
59                      Bethel Baptist Church Cemetery
60                                    Merrell Cemetery
61                               St. Monica's Cemetery
62                                      Naval Cemetery
63                             Knollwood Park Cemetery
64                                 St. Anns Churchyard
65                         New/Middle Dutch Churchyard
66                              United Hebrew Cemetery
67                                      Riker Cemetery
68                     African Burial Ground, Flatbush
69                                  Wallabout Cemetery
70        St. Peter's Church Cemetery, Westchester sq.
71                    Friend Cemetery, Westchester sq.
72                               Jones's Wood Cemetery
73                               Baron Hirsch Cemetery
74                                    Newtown Cemetery
75                               Mount Olivet Cemetery
76                                   Barkeloo Cemetery
77                      Ursuline Sister Burial Grounds
78                  Amity Street Baptist Burial Ground
79                                 St. Mary's Cemetery
80   Bayside Cemetery, Mokom Sholom cemetery& Acaci...
81                         Public Burial Ground,Queens
82                                   New Lots Cemetery
83                       Bethel A.M.E. Church Cemetery
84                       African Burial Ground, Harlem
85                 St. Mary of the assumption cemetery
86                      Public Burial Ground, Flushing
87                           Macedonia A.M.E Cemetery,
88                    Friend's Cemetery, Prospect Park
89              Public Burial Ground, East 50th Street
90                   Public Burial Ground, Bryant Park
91        Public Burial Ground, Washington square Park
92           Public Burial Ground, Madison Square Park
93                           Alm's House Burial Ground
94                               Kings County Cemetery
95                    18th Street Methodist Churchyard
96                            Merchant Marine Cemetery
97                     African Burial Ground, Elmhurst
98                                   Canarsie Cemetery
99                      Underhill Family Burial Ground
100    Spring Street Presbyterian Church Burial Vaults
101                    Fredrick Douglass Memorial Park
102                        Friend's Cemetery, Flushing
103                                Holy Cross Cemetery
104       Quarantine Cemeteries, Tompkinsville (North)
105       Quarantine Cemeteries, Tompkinsville (South)
106                  Quarantine Cemeteries, Silverlake
107             Quarantine Cemeteries, Seguine's Point
108                            Mount richmond Cemetery
109                             Rantus Family Cemetery
110                                 Machpelah Cemetery
111                   New Union Field/Beth-El Cemetery
112                               Union Field Cemetery
113                     Hungarian Union Field Cemetery
114                      African Burial Ground, Inwood
115                               Linden Hill Cemetery
116                 Friends Cemetery, East Houston St.
117         Prebysterian Cemeteries, South Houston St.
118         Reformed Dutch Cemetery, South Houston St.
119                         Methodist Episcopal Church
120                Baptist Cemetery, North Houston St.
121                         Methodist Society Cemetery
122         Maimonides Cemetery & Mount Hope Cemetery
123                         A.M.E Zion Church Cemetery
124                                Montefiore Cemetery
125           Citizen's Union/ Mount Pleasant Cemetery
126                              Cypress Hill Cemetery
127             African Burial Ground, Chrystie Street
128                        Ferris Family Burial Ground
129               B'nai Jeshurun Cemetery, 32nd Street
130                            Calvary Cemetery (West)
131                            Calvary Cemetery (East)
132                     Cypress Hill National Cemetery
133                                    Pelham Cemetery
134                                Mount Zion Cemetery
135               Rossville A.M.E Zion Church cemetery
136                      Sailor's Snug Harbor Cemetery
137                          Burroughs Family Cemetery
138                  St Johns Cemetery, Middle Village
139                             Remsen Family Cemetery
140                                Washington Cemetery
141                           St. Raymond New Cemetery
142                           St. Raymond New Cemetery
143                Jesuit Cemetery, Fordham University
144                               Mount Judah Cemetery
145                                     Nagel Cemetery
146                                  Bensonia Cemetery
147                        Sisters of Charity Cemetery
148                      Cornell Cemetery, Little Neck
149                         The Marble Cemetery (West)
150                       The Marble Cemeteries (East)
151                             St. raymond Churchyard
152                         Most Holy Trinity Cemetery
153                              Brinckerhoff Cemetery
154                               St. James churchyard
155                       Schenck Family Burial ground
156   St. Mark's in the Bowery Churchyard and cemetery
157                 Van Cortlandt family Burial Ground
158                          Kingsbridge Burial Ground
159       Cedar Grove Cemetery & Mount Hebron Cemetery
160                       Willett Family Burial Ground
161                                     Union Cemetery
162                              Mount Carmel Cemetery
163                               Mount Neboh Cemetery
164                           Southside Burial Ground
165                          Wyckoff Snediker Cemetery
166                              St. Fidelis Graveyard
167                              Salem Fields Cemetery
168  Fourth Shearith Israel Cemetery/ Beth Olem Cem...
169                              St. Luke's Churchyard
170                             St. Paul's Churchyard
171                   Carmine Street Lutheran Cemetery
172                             Mount Lebanon Cemetery
173             St. John's Cemetery, Greenwich Village
174                        Hopper Family Burial Ground
175             St. Patrick's old cathedral's cemetery
176                     St. Peter's Catholic Graveyard
177                     Third Shearith Israel Cemetery
178                    Second Shearith Israel Cemetery
179                     First Shearith Israel Cemetery
180                      Passionist Monastery Cemetery
181                      11th Street Catholic Cemetery
182                              Johnson Burial Ground
183                            French Church of Esprit
184                      Strattonport Village Cemetery
185                       Indian Cemetery, Little Neck
186                      Leverich Family Burial Ground
187  The New Burial Place without the gate of the city
188                 The old Graveyard of new Amsterdam

    Number of Churches Nearby
0                          57
1                          53
2                           4
3                           2
4                          34
5                          59
6                          19
7                           8
8                          47
9                          60
10                         60
11                         19
12                          1
13                         45
14                         31
15                         32
16                         48
17                          2
18                         38
19                         40
20                         21
21                         39
22                         34
23                         60
24                          7
25                         13
26                         38
27                         21
28                         60
29                         41
30                         60
31                         41
32                          8
33                         60
34                          1
35                         30
36                         21
37                         60
38                         60
39                         15
40                         22
41                         23
42                         19
43                         44
44                         51
45                         60
46                         37
47                         60
48                         60
49                         14
50                          0
51                         49
52                          0
53                          8
54                         50
55                          9
56                          6
57                         60
58                         16
59                         60
60                          6
61                         60
62                         19
63                         19
64                         60
65                         36
66                          3
67                          4
68                         60
69                         26
70                         33
71                         33
72                         30
73                          5
74                         38
75                          5
76                          9
77                         60
78                         60
79                          1
80                         23
81                         45
82                         60
83                         47
84                         59
85                         13
86                         50
87                         60
88                         15
89                         55
90                         60
91                         60
92                         60
93                          0
94                         60
95                         54
96                          3
97                         43
98                         44
99                         60
100                        42
101                         2
102                        60
103                        60
104                        16
105                        14
106                         6
107                         1
108                         3
109                         8
110                         8
111                        12
112                         8
113                         9
114                        19
115                        31
116                        60
117                        60
118                        60
119                        60
120                        60
121                        60
122                        24
123                        42
124                        23
125                        60
126                        14
127                        60
128                        27
129                        60
130                         7

In [ ]:
import time
# Making a deep copy of the current filtered dataFrame

def fetch_all_places(api_key, location,place_type, radius =500):
    # Google Places API endpoint
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # Initial parameters for the API request
    params = {
        'key': API_KEY,
        'location': location,
        'radius': radius,
        'type': place_type
    }

    # List to store all places
    places = []
    counter = 0
    while True:
    # Make the API request
      response = requests.get(url, params=params)
      res = response.json()

    # Check if the request was successful
      if res['status'] == 'OK':
        # Extract places
        places.extend([(place['name'], place['vicinity']) for place in res['results']])
        counter += 1
        print("Counter: ", counter)
        # Check for the presence of a 'next_page_token' in the response
        if 'next_page_token' in res:
            params['pagetoken'] = res['next_page_token']
        else:
            break  # No more pages to fetch

        # Important: There is a short delay needed between requests for the next page token to become valid
        time.sleep(2)
      else:
        print("Failed to fetch results:", res['status'])
        break

    return len(places)


#store the churh places close to  a place
places = []
# Update DataFrame with the count of nearby churches
# Assume df is your DataFrame and already imported
for i in range(len(df_exist)):
  row = df_exist.iloc[i]
  lat, lon = row['Latitude'], row['Longitude']
  churches_count = fetch_all_places(api_key, location, place_type, radius)
  df_copy.at[i,'Number of Churches Nearby']= churches_count


# Optionally, save the updated DataFrame
df_exist.to_csv('updated_cemetery_data.csv', index=False)
df_copy.to_csv('updated_cemetery_data.csv', index=False)

# Display the DataFrame for verification
pd.set_option('display.max_rows', None)
# Print every entry in the 'Number of Churches Nearby' column
print(df_copy['Number of Churches Nearby'].to_string())

print(df_copy[['Name', 'Number of Churches Nearby']])

KeyError: 'Latitude'

In [ ]:
def get_nearby_churches_count(lat, lon, radius=1000):
    location = f'{lat},{lon}'
    place_type = 'church'

    url = (
        f'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
        f'?location={location}'
        f'&radius={radius}'
        f'&type={place_type}'
        f'&key={API_KEY}'
    )

    response = requests.get(url)
    places = response.json()

    # Count the number of church results returned
    count = len(places.get('results', []))
    return count

get_nearby_churches_count(-74.011873,40.708411)

0

In [ ]:
df['Latitude']
df['Longitude']

0     -73.952726
1     -74.006439
2     -74.147084
3     -73.883285
4     -74.007490
         ...
184   -73.843246
185   -73.736872
186   -73.894548
187   -74.011873
188   -74.013348
Name: Longitude, Length: 189, dtype: float64